name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  validate:
    uses: INENI-PT-GROUP-B/.github/.github/workflows/pr-title-reusable.yml@main
